version: 2
jobs:
  build:
    docker:
      - image: golang:1.12
      - image: redis
      - image: memcached

    working_directory: /go/src/github.com/abraithwaite/jeff

    steps:
      - checkout

      - run:
          name: Run tests
          command: make test
          environment:
            GO111MODULE: "on"
